### ISSUE TITLE
markuplintがインストールされていないプロジェクトでクラッシュする

### ISSUE THREAD

**Issue by kagankan** [markuplint/vscode-markuplint#8]
@YusukeHirao 
便利な拡張の提供いつもありがとうございます！　以下、markuplintを使用していないプロジェクトでの問題の報告になります。

## 環境

Windows 10
markuplint v2.0.3
VSCode v1.66.0
（macOSでも同様の現象を確認しています）

## 現象

vscode-markuplintの拡張機能をインストールした状態で、
markuplintのnpmパッケージをインストールしていない（ ＝`./node_modules/markuplint` が存在しない）プロジェクトを開くと、拡張の起動中にクラッシュして以下のエラーが出ます。

![image](https://user-images.githubusercontent.com/34136752/162564535-5765b327-b095-4ae8-817e-219d75d4c279.png)

### 出力

```
Started: markuplint language server
Search markuplint on: c:\Users\Owner\project\node_modules\markuplint
Error: Cannot find module 'c:\Users\Owner\project\node_modules\markuplint'
Require stack:
- c:\Users\Owner\.vscode\extensions\yusukehirao.vscode-markuplint-2.0.3\out\server\index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:987:15)
    at Module._load (node:internal/modules/cjs/loader:832:27)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1059:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (c:\Users\Owner\.vscode\extensions\yusukehirao.vscode-markuplint-2.0.3\out\server\index.js:17:18)
    at Module._compile (node:internal/modules/cjs/loader:1163:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1216:10)
    at Module.load (node:internal/modules/cjs/loader:1035:32)
    at Module._load (node:internal/modules/cjs/loader:876:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'c:\\Users\\Owner\\.vscode\\extensions\\yusukehirao.vscode-markuplint-2.0.3\\out\\server\\index.js'
  ]
}
node:internal/modules/cjs/loader:990
  throw err;
  ^

Error: Cannot find module 'debug'
Require stack:
- c:\Users\Owner\.vscode\extensions\yusukehirao.vscode-markuplint-2.0.3\node_modules\@markuplint\ml-core\lib\debug.js
- c:\Users\Owner\.vscode\extensions\yusukehirao.vscode-markuplint-2.0.3\node_modules\@markuplint\ml-core\lib\ml-core.js
- c:\Users\Owner\.vscode\extensions\yusukehirao.vscode-markuplint-2.0.3\node_modules\@markuplint\ml-core\lib\index.js
- c:\Users\Owner\.vscode\extensions\yusukehirao.vscode-markuplint-2.0.3\node_modules\markuplint-v1\lib\lint-file.js
- c:\Users\Owner\.vscode\extensions\yusukehirao.vscode-markuplint-2.0.3\node_modules\markuplint-v1\lib\lint.js
- c:\Users\Owner\.vscode\extensions\yusukehirao.vscode-markuplint-2.0.3\node_modules\markuplint-v1\lib\index.js
- c:\Users\Owner\.vscode\extensions\yusukehirao.vscode-markuplint-2.0.3\out\server\index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:987:15)
    at Module._load (node:internal/modules/cjs/loader:832:27)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1059:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (c:\Users\Owner\.vscode\extensions\yusukehirao.vscode-markuplint-2.0.3\node_modules\@markuplint\ml-core\lib\debug.js:5:46)
    at Module._compile (node:internal/modules/cjs/loader:1163:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1216:10)
    at Module.load (node:internal/modules/cjs/loader:1035:32)
    at Module._load (node:internal/modules/cjs/loader:876:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'c:\\Users\\Owner\\.vscode\\extensions\\yusukehirao.vscode-markuplint-2.0.3\\node_modules\\@markuplint\\ml-core\\lib\\debug.js',
    'c:\\Users\\Owner\\.vscode\\extensions\\yusukehirao.vscode-markuplint-2.0.3\\node_modules\\@markuplint\\ml-core\\lib\\ml-core.js',
    'c:\\Users\\Owner\\.vscode\\extensions\\yusukehirao.vscode-markuplint-2.0.3\\node_modules\\@markuplint\\ml-core\\lib\\index.js',
    'c:\\Users\\Owner\\.vscode\\extensions\\yusukehirao.vscode-markuplint-2.0.3\\node_modules\\markuplint-v1\\lib\\lint-file.js',
    'c:\\Users\\Owner\\.vscode\\extensions\\yusukehirao.vscode-markuplint-2.0.3\\node_modules\\markuplint-v1\\lib\\lint.js',
    'c:\\Users\\Owner\\.vscode\\extensions\\yusukehirao.vscode-markuplint-2.0.3\\node_modules\\markuplint-v1\\lib\\index.js',
    'c:\\Users\\Owner\\.vscode\\extensions\\yusukehirao.vscode-markuplint-2.0.3\\out\\server\\index.js'
  ]
}
[Info  - 16:38:27] Connection to server got closed. Server will restart.
Started: markuplint language server
（以下繰り返し）
```

## 原因

拡張に必要なnpmパッケージ（中でも、プロジェクトでmarkuplintがインストールされていない場合の処理で必要なパッケージ）がインストールされていないようです。

## （一時的な）解決

`c:\\Users\\Owner\\.vscode\\extensions\\yusukehirao.vscode-markuplint-2.0.3` に移動して`npm install` を実行してVSCodeを再起動したところ問題は解決し、

```
<markuplint> ワークスペースのnode_modulesにmarkuplintが発見できなかったためVS Code拡張にインストールされているバージョン(v1.11.4)を利用します。
```

のメッセージが出るようになりました。

必要なnpmパッケージが含まれるように修正いただけますでしょうか？

**Comment by ark-tds** [comment]
いつも markuplint を便利に活用しております！
私も markuplint がインストールされていないプロジェクトで同じ現象が起きています。
解決を願っております🙏

## 環境

macOS v12.1
VSCode: v1.66.0
markuplint v2.0.3

**Comment by YusukeHirao** [comment]
@kagankan
ご報告ありがとうございます。
確認して対処します。

**Comment by YusukeHirao** [comment]
@kagankan 
@ark-tds 

バグ修正といくつかの改善を加えて2.1.0をパブリッシュしました。ご確認ください。

**Comment by kagankan** [comment]
@YusukeHirao 
ご対応ありがとうございます！
アップデートして、問題が解決されたことを確認できました！👏

**Comment by ark-tds** [comment]
@YusukeHirao 
ありがとうございます！現状の 2.1.1 でも問題ありません👍
